config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  namespace :admin do
    get 'home', to: 'pages#home'
    resources :users
    resources :categories do
      resources :words
      member do
        get :words
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about', to: "static_pages#about"

  get '/signup', to: "users#new"
  get '/dashboard', to: "users#dashboard"

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  resources :users do # routes に /users/:id/following  /users/:id/followers　ができる
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :lessons do
    resources :answers
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy

  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 100 }

  def active_words
    Word.where(category_id: id)
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  
  has_many :words, through: :answers

  has_many :choices, through: :answers

  has_one :activity, as: :action

  def next_word
    (category.words - words).first
  end

  def lesson_results
    choices.where(correct: true).count
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :activity, as: :action

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true

  after_create :relationship_activity

  def relationship_activity
    create_activity(user: follower)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }

  has_many :active_relationships, class_name: "Relationship",
          foreign_key: "follower_id",
          dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  
  has_many :passive_relationships, class_name:  "Relationship",
          foreign_key: "followed_id",
          dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :lessons, dependent: :destroy
  has_many :activities, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 3, maximum: 65 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 3 }, allow_nil: true

  mount_uploader :image, ImageUploader

  def active_relationships
    Relationship.where(follower_id: id)
    # follower_id = id  # フォローした人を探す
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end

  def following
    ids = active_relationships.pluck(:followed_id)  # follower_id　だけ取り出す
    User.where(id: ids) # follower_id の詳細（name,emal,passwor）はUserテーブルが持っているのでそこに見に行く
  end


  def follow(other_user)  #ここでデータベースにデータを登録してる
    Relationship.create(
      follower_id: id,
      followed_id: other_user.id
    )
  end

  def relationship(other_user)
    active_relationships.find_by(
      followed_id: other_user.id
    )
  end

  # ユーザーをフォローする
  def add(other_user)
    adding << other_user
  end

  # ユーザーをフォロー解除する
  def remove(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def adding?(other_user)
    adding.include?(other_user)
  end

  def lesson_taken(cat_id)
    lesson = lessons.find_by(category_id: cat_id)
  end

end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  validates :category_id, presence: true
  validates :content, presence: true
  validate :has_one_correct_answer, :has_unique_choices

  def correct_answer
    choices.find_by(correct:true).try(:content)
  end

  def has_one_correct_answer
    if choices.select{ |choice| choice.correct? }.count != 1
      return errors.add :base, "Must have one correct choice"
    end
  end

  def has_unique_choices
    if choices.uniq{ |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end 
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @lesson = Lesson.find(params[:lesson_id])
    @category = Category.find_by(id: @lesson.category_id)
    if @lesson.next_word.nil?
      @lesson.create_activity(user: current_user)
      @lesson.update(result: @lesson.lesson_results)
      redirect_to lesson_url(@lesson)
    else
    end
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @answer = @lesson.answers.build(answer_params)
    if @answer.save
      redirect_to new_lesson_answer_url(@lesson)
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:word_id, :choice_id)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def create
    @category = Category.find(params[:category_id])
    @lesson = @category.lessons.build(user: current_user)
    if @lesson.save
      redirect_to new_lesson_answer_url(@lesson)
    else
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
    @answers = @lesson.answers.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :required_login, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Welcome to Elearning System"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.paginate(page: params[:page], per_page: 10)
  end

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(users_params)
      redirect_to user_url(@user)
    else 
      render 'edit'
    end
  end

  def following
    @user = User.find(params[:id])
    @title = "Following"
    @users = @user.following.paginate(page: params[:page])
    render "users/follow"
  end

  def followers
    @user = User.find(params[:id])
    @title = "Follower"
    @users = @user.followers.paginate(page: params[:page])
    render "users/follow"
  end

  def dashboard
    @activities = Activity.where("user_id IN (?) OR user_id = ? ", current_user.following_ids, current_user.id ).paginate(page: params[:page], per_page: 10)
  end

  
  private
    def users_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache, :remove_image)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Elearning System"
    if page_title.empty?
    base_title
    else
    "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def signed_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/home.html.erb
<h1 class="text-center">Admin page</h1>
<br>
<div class="container">
    <div class="row">
        <div class="col m-2 text-center">
            <div class="m-3"><%= link_to "Categories", admin_categories_path, class: "btn btn-info" %></div>
            <p>You can edit Categories.</p>
        </div>

        <div class="col m-2 text-center ">
            <div class="m-3"><%= link_to "Users", admin_users_path, class: "btn btn-info" %></div>
            <p>You can edit Users.</p>
        </div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        This form contains errors.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg|  %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_feeds.html.erb
    <div class="row">
        <% if @activities.any? %>
            <% @activities.each do |activity| %>
                <div class="col-md-3">
                    <% if activity.user.image? %>
                        <p><%= image_tag activity.user.image.thumb.url %></p>
                    <% else %>
                        <p><%= image_tag("default.jpg", :size => "50x50") %></p>
                    <% end %>
                </div>
                
                <div class="col-md-9 mb-3">
                    <% if activity.action_type == "Lesson" %>
                        <% if activity.user == current_user %>
                            <p><%= link_to "You", user_path(current_user)  %> learned
                                <%= activity.action.result %> of <%= activity.action.category.words.count %>
                                in <%= link_to activity.action.category.title, lesson_path(activity.action.id) %>
                            </p>
                        <% else %>
                            <p><%= link_to activity.user.name, user_path(activity.user)  %> learned
                                <%= activity.action.result %> of <%= activity.action.category.words.count %>
                                in <%= link_to activity.action.category.title, lesson_path(activity.action.id) %>
                            </p>
                        <% end %>
                    <% else %>
                        <% followed_user = User.find_by(id: activity.action.followed_id) %>
                        <% if activity.user == current_user %>
                            <p>
                                <%= link_to "You", user_path(current_user) %> followed 
                                <%= link_to followed_user.name, user_path(followed_user) %>
                            </p>
                        <% else %>
                            <p>
                                <%= link_to activity.user.name, user_path(activity.user) %> followed 
                                <%= link_to followed_user.name, user_path(followed_user) %>
                            </p>
                        <% end %> 
                        
                    <% end %>
                    <div>
                        <small><%= time_ago_in_words(activity.created_at) %> ago.</small>
                    </div>
                </div>
            <% end %>
        <% else %>
            <h5>Nothing to show</h5>    
        <% end %>
    </div>


<div class="apple_pagination">
    <%= will_paginate @activities %>
</div>

app/views/shared/_user_info.html.erb
    <div class="row">
        <div class="col-md-8">
            <div class="media">
                <div class="media-body">
                    <%= image_tag @user.image.to_s %>
                    <div class="text-center mt-3 mb-1">
                        <% unless current_user ==  @user %>
                            <% unless current_user.relationship(@user) %>
                                <%= button_to "Follow", relationships_path, params: {followed_id: @user.id}, class: "btn btn-sm btn-success" %>
                            <% else %>
                                <%= button_to "Unfollow", relationship_path(current_user.relationship(@user)), method: :delete, class: "btn btn-sm btn-danger" %>
                            <% end %> 
                        <% end %>
                    </div>
                    <h2 class="text-center"><%= @user.name %></h2>
                    
                    <% if current_user.admin? && @user == current_user %>
                        <div class="text-center m-2"><%= link_to "Admin", admin_home_path, class: "btn btn-info" %></div>
                    <% end %>

                    <div class="row">
                        <div class="col m-2">
                        <h3>
                            <%= link_to @user.active_relationships.count, following_user_path(@user) %>
                        </h3>
                        following
                        </div>
                        <div class="col m-2">
                        <h3>
                            <%= link_to @user.passive_relationships.count, followers_user_path(@user) %>
                        </h3>
                        followers
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </div>