config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  namespace :admin do
    get 'home', to: 'pages#home'
    resources :users
    resources :categories do
      resources :words
      member do
        get :words
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about', to: "static_pages#about"

  get '/signup', to: "users#new"
  get '/dashboard', to: "users#dashboard"

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  resources :users do # routes に /users/:id/following  /users/:id/followers　ができる
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :lessons do
    resources :answers
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  validates :category_id, presence: true
  validates :content, presence: true
  validate :has_one_correct_answer, :has_unique_choices

  def correct_answer
    choices.find_by(correct:true).try(:content)
  end

  def has_one_correct_answer
    if choices.select{ |choice| choice.correct? }.count != 1
      return errors.add :base, "Must have one correct choice"
    end
  end

  def has_unique_choices
    if choices.uniq{ |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end 
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :required_login, :admin_user

  def index
    @category = Category.find(params[:category_id])
    @words = @category.words
  end

  def new
    @category = Category.find(params[:category_id])
    @word = @category.words.build
    3.times { @word.choices.build }
  end

  

  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.build(words_params)

    if @word.save
      flash[:success] = "Successfully Created"
      redirect_to admin_category_words_url
    else
      render 'new'
    end

  end

  def edit
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
  end


  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    if @word.update_attributes(words_params)
      flash[:success] = "Successfully changed"
      redirect_to admin_category_words_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    @word.destroy
    flash[:success] = "Successfully deleted"
    redirect_to admin_category_words_url
  end

  private
   def words_params
    params.require(:word).permit(:content, choices_attributes: [:id, :content, :correct])
   end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @category, @word] do |f| %>
    <%= render "shared/error_messages", object: @word %>
    <div class="form-group">
        <%= f.text_field :content, placeholder: "Word", class: "form-control mb-4" %>
    </div>

    <div class="form-group">
        <% label_tag "choices" %>
        <%= f.fields_for :choices do |choice|  %>
        <%= choice.text_field :content, class: "form-control" %>
        <%= choice.check_box :correct, class: "d-inline" %>
        <p class="d-inline">This is the correct answer! </p>
        <% end %>
    </div>
    
    <%= f.submit  "Create", class: "btn btn-block btn-info" %>
<% end %>

app/views/admin/words/edit.html.erb
<div class="row">
    <div class="col-md-5 mx-auto">
        <div class="container">
            <h1 class="text-center">Edit Word</h1>
            <br>
            <%= render "form" %>

           <div class="text-center">
            <%= link_to "Back", admin_category_words_path, class: "btn btn-link" %>
        </div>
        </div>
    </div>
</div>

app/views/admin/words/index.html.erb
<h2 class="ml-3"><%= @category.title %></h2>

<div class="container">
    <div class="new-category mb-2 text-right">
        <%= link_to  'New Word', new_admin_category_word_path, class:"btn btn-sm btn-outline-primary" %>
    </div>
        
        <% @words.each do |word| %>
            <div class="row">
                <div class="col-md-4">
                    <%= word.content %> 
                </div>

                <div class="col-md-4">
                    <%= word.correct_answer %>
                </div>
                <div class="col-md-4 text-right">
                    <%= link_to "Edit", edit_admin_category_word_path(@category, word), class: "btn btn-sm btn-outline-info" %>
                    <%= link_to "Delete", admin_category_word_path(@category, word), class: "btn btn-sm btn-outline-danger", method: :delete, data: {confirm: 'Are you sure?' } %>
                </div>
            </div>
        <% end %>
        <div class="text-center">
            <%= link_to "Back", admin_categories_path, class: "btn btn-link" %>
        </div>
    </div>
</div>

app/views/admin/words/new.html.erb
<div class="row">
    <div class="col-md-5 mx-auto">
        <div class="container">
            <h1 class="text-center">New Word</h1>
            <br>
            <%= render "form" %>

           <div class="text-center">
            <%= link_to "Back", admin_category_words_path, class: "btn btn-link" %>
        </div>
        </div>
    </div>
</div>

app/views/admin/words/show.html.erb
<h1 class="text-center">Word</h1>