config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  namespace :admin do
    get 'home', to: 'pages#home'
    resources :users
    resources :categories do
      resources :words
      member do
        get :words
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about', to: "static_pages#about"

  get '/signup', to: "users#new"
  get '/dashboard', to: "users#dashboard"

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  resources :users do # routes に /users/:id/following  /users/:id/followers　ができる
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :lessons do
    resources :answers
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy

  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 100 }

  def active_words
    Word.where(category_id: id)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :required_login, :admin_user

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:success] = "Successfully created"
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(categories_params)
      flash[:success] = "Successfully changed"
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = "Successfully deleted"
    redirect_to admin_categories_url
  end

  private
    def categories_params
      params.require(:category).permit(:title, :description)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6).order('created_at DESC')
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <div class="container">
                <h1 class="text-center">Edit category</h1>
                <br>

                <%= form_for [:admin, @category] do |f| %>
                    <div class="form-group">
                        <%= f.text_field :title, class: "form-control mb-4" %>
                    </div>

                    <div class="form-group">
                        <%= f.text_field :description, class: "form-control mb-4" %>
                    </div>

                    <%= f.submit "Save", class: "btn btn-block btn-info" %>
                <% end %>
                <div class="text-center">
                    <%= link_to "Back", admin_categories_path, class: "btn btn-link" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<h4 class="ml-3">Categories</h4>


<div class="container">
    <div class="new-category mr-2 text-right">
        <%= link_to "Create New", new_admin_category_path, class: "btn btn-sm btn-outline-primary" %></div>
    </div>
    <% @categories.each do |category| %>
        <div class="row m-2">
            <div class="col-md-3">
                <%= link_to category.title, admin_category_words_path(category) %>
            </div>
            <div class="col-md-6">
                <%= category.description %>
            </div>
            <div class="col-md-3 text-right">
                 <%= link_to "Edit", edit_admin_category_path(category), class: "btn btn-sm btn-outline-info" %>
                 <%= link_to "Delete", admin_category_path(category), class: "btn btn-sm btn-outline-danger", method: :delete, data: {confirm: 'Are you sure?' } %>
            </div>
        </div>
    <% end %>
</div>

<div class="apple_pagination">
    <%= will_paginate %>
</div>

app/views/admin/categories/new.html.erb
<div class="row">
    <div class="col-md-5 mx-auto">
        <div class="container">
            <h1 class="text-center">Create category</h1>
            <br>

            <%= form_for [:admin, @category] do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <div class="form-group">
                    <%= f.text_field :title, placeholder: "Title", class: "form-control mb-4" %>
                </div>

                <div class="form-group">
                    <%= f.text_field :description, placeholder: "Description", class: "form-control mb-4" %>
                </div>

                <%= f.submit "Create", class: "btn btn-block btn-info" %>
            <% end %>
            <div class="text-center">
                <%= link_to "Back", admin_categories_path, class: "btn btn-link" %>
            </div>
        </div>
    </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container">
    <% @categories.each do |category| %>
        <div class="row">
            <div class="col-md-3">
                <%= category.title %>
            </div>
            <div class="col-md-6">
                <%= category.description %>
            </div>
        </div>
    <% end %>
</div>