config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'
  get 'lessons/create'
  get 'lessons/show'
  namespace :admin do
    get 'home', to: 'pages#home'
    resources :users
    resources :categories do
      resources :words
      member do
        get :words
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  get '/about', to: "static_pages#about"

  get '/signup', to: "users#new"
  get '/dashboard', to: "users#dashboard"

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

  resources :users do # routes に /users/:id/following  /users/:id/followers　ができる
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :categories
  resources :lessons do
    resources :answers
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy

  has_many :lessons, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 3, maximum: 100 }

  def active_words
    Word.where(category_id: id)
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :required_login, :admin_user

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      flash[:success] = "Successfully created"
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(categories_params)
      flash[:success] = "Successfully changed"
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:success] = "Successfully deleted"
    redirect_to admin_categories_url
  end

  private
    def categories_params
      params.require(:category).permit(:title, :description)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6).order('created_at DESC')
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% provide(:title, 'Lessons') %>

<h1 class="text-center">Lessons</h1>
<br>

<div class="container">
    <div class="row">
        <% @categories.each do |category| %>
            <div class="col-lg-6">
                <div class="card text-left">

                <div class="card-header">
                    <div class="row">
                        <div class="col-md-9">
                            <h4 class="card-title"><%= category.title %></h4>
                        </div>
                        <div class="col-md-3 text-right">
                            <p><%= category.active_words.count %> words</p>
                        </div>
                    </div>
                </div>

    

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <p class="card-text"><%= category.description %></p>
                            </div>
                            <div class="col-md-3 text-right">
                                <% lesson = current_user.lesson_taken(category.id) %>
                                <% if lesson.nil? %>
                                    <p><%= link_to "Start Lesson", lessons_path(category_id: category.id), method: :post, class: "btn btn-sm btn-outline-info"%></p>
                                <% else %>
                                    <p><%= link_to "Show result", lesson_path(lesson.id), class: "btn btn-sm btn-outline-danger" %></p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

<div class="apple_pagination">
    <%= will_paginate %>
</div>